---
title: Camila L.Oliveira
author: Camila L. Oliveira
email: support@forestry.io
description: em breve
baseurl: "/ubuild-jekyll"
url: https://db-j6o-qnukgxa.instant.forestry.io/
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
